chore: test lighthouse

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,70 +10,41 @@ on:
     paths:
       - 'docs/**'
       - 'packages/wilson/**'
+      - 'netlify.toml'
       - 'yarn.lock'
   workflow_dispatch:
 
 jobs:
-
-  # This job will
+  # If, for whatever reason, the userland netlify deploy action doesn't
+  # work anymore, this can be switched to build & deploy on netlify via
+  # netlify.toml and waiting for netlify deployment with
+  # https://github.com/marketplace/actions/wait-for-netlify-deployment
+  # Netlify will
   #   - deploy a preview every time there is a PR to the main branch
   #     opened, synchronized or reopened
   #   - comment on that PR with the preview deploy URL
   deployPreview:
-    name: Deploy preview to Netlify
     runs-on: ubuntu-latest
     if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
 
     steps:
       - uses: actions/checkout@v2
 
-      - name: Setup Node.js 14.x
-        uses: actions/setup-node@v2
+      - uses: actions/setup-node@v2
         with:
           node-version: 14.x
 
-      - name: Set yarn cache dir as output
-        id: cache-dir
-        run: echo "::set-output name=dir::$(yarn cache dir)"
-
-      - name: Cache dependencies
-        id: cache
-        uses: actions/cache@v2
-        env:
-          cache-name: cache-node-modules
+      - name: Wait for Netlify Deploy
+        uses: probablyup/wait-for-netlify-action@3.2.0
+        id: waitForDeployment
         with:
-          path: |
-            ${{ steps.cache-dir.outputs.dir }}
-            node_modules
-            */*/node_modules
-          key: ${{ runner.os }}-yarn-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-yarn-${{ env.cache-name }}-
-            ${{ runner.os }}-yarn-
-            ${{ runner.os }}-
-
-      - name: Install Dependencies
-        if: steps.cache.outputs.cache-hit != 'true'
-        run: yarn --frozen-lockfile
-
-      - name: Build wilson
+          site_id: ${{ secrets.NETLIFY_SITE_ID }}
         env:
-          NODE_ENV: production
-        run: |
-          yarn wilson:build
+          NETLIFY_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
 
-      - name: Build website
+      - name: Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.waitForNetlifyDeploy.outputs.url }} || echo "LHCI failed!"
         env:
-          NODE_ENV: production
-        run: |
-          yarn docs:build
-
-      - name: Deploy website to Netlify
-        uses: South-Paw/action-netlify-deploy@v1.2.0
-        with:
-          github-token: ${{ secrets.RELEASE_TOKEN }}
-          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
-          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
-          build-dir: './docs/dist'
-          draft: true
-          comment-on-pull-request: true
+          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
